SELECT * FROM BOARD ORDER BY GUBN DESC, BGNO DESC, BGORD
SELECT * FROM MEMBER
SELECT * FROM COMMENT ORDER BY CGNO DESC, CGORD
SELECT * FROM GOOD



SELECT CID, CGNO, CGDEPTH FROM COMMENT WHERE CGNO = 2 AND CGDEPTH >= 2 ORDER BY CGNO DESC, CGORD

SELECT BID, BGNO, BGDEPTH FROM BOARD WHERE BGNO = 2 AND BGDEPTH >= 5 ORDER BY GUBN DESC, BGNO DESC, BGORD
/*같은 그룹에 이전값이 있을때*/
SELECT BID, GUBN, BGNO, BGORD, BGDEPTH
FROM BOARD
WHERE BGNO = 4
AND BGORD = (SELECT MAX(BGORD)
			FROM BOARD
			WHERE BGNO=4
			AND BGORD<7)
/*같은 그룹에 이전값이 없어서 이전 그룹값을 찾을때*/
SELECT BID, GUBN, BGNO, BGORD, BGDEPTH
FROM BOARD
WHERE BGNO=(
			SELECT MIN(BGNO)
			FROM BOARD
			WHERE BGNO>4
			   AND GUBN='N')
	AND BGORD=(
			SELECT MAX(BGORD)
			FROM BOARD
			WHERE BGNO = (
						SELECT MIN(BGNO)
						FROM BOARD
						WHERE BGNO>4))
	AND GUBN='N'

/*같은 그룹에 다음값이 있을때*/
SELECT BID, GUBN, BGNO, BGORD, BGDEPTH
FROM BOARD
WHERE BGNO = 2
AND BGORD = (SELECT MIN(BGORD)
			FROM BOARD
			WHERE BGNO=2
			AND BGORD>2)

/*같은 그룹에 다음값이 없어서 다음 그룹값을 찾을때*/
SELECT BID, GUBN, BGNO, BGORD, BGDEPTH
FROM BOARD
WHERE BGNO=(
			SELECT MAX(BGNO)
			FROM BOARD
			WHERE BGNO<4
			AND GUBN='N')
	AND BGORD=0
	AND GUBN='N'


SELECT MIN(BGNO)
FROM BOARD 
WHERE GUBN='N'

SELECT MIN(BGNO)
FROM BOARD

SELECT MAX(BGORD)
FROM BOARD
WHERE BGNO = (SELECT MIN(BGNO)
				FROM BOARD)

/*'//같은 그룹에 다음값이 있을때*/
SELECT MAX(BGORD)
FROM BOARD
WHERE BGNO=4


SELECT BID, GUBN, BGNO, BGORD, BGDEPTH 
FROM BOARD 
WHERE BGNO = 6
 AND BGORD = (SELECT MIN(BGORD)
				FROM BOARD
				WHERE BGNO=6 
				AND BGORD>0)

/*그룹 깊이가 줄기 전까지 삭제*/
UNTIL BGDEPTH < RS(DEPTH)
DELETE BOARD WHERE BGNO=1
             AND BGORD>2

			

SELECT * FROM BOARD WHERE BGNO = 4 AND BGDEPTH >= 3